apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - vers=3.0
    - actimeo=30
    - noperm
    - serverino
  csi:
    driver: file.csi.azure.com
    volumeHandle: "${VOLUME_HANDLE}"
    volumeAttributes:
      storageaccount: "${STORAGE_ACCOUNT}"
      shareName: "${FILE_SHARE_NAME}"
      clientID: ${CLIENT_ID}
      resourcegroup: "${RESOURCE_GROUP}"
      protocol: smb 