apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-blob-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 5Gi 