apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: blob-static-pv
  storageClassName: azureblob-fuse-premium 